FROM node:lts-alpine as builder
ENV NODE_ENV production

ARG VITE_APP_MONDAY_API_VERSION
ENV VITE_MONDAY_API_VERSION=$VITE_MONDAY_API_VERSION
ARG VITE_MANAGEMENT_API
ENV VITE_MANAGEMENT_API=$VITE_MANAGEMENT_API
ARG VITE_MONDAY_APP_ID
ENV VITE_MONDAY_APP_ID=$VITE_MONDAY_APP_ID
ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ARG VITE_MICROSOFT_CLIENT_ID
ENV VITE_MICROSOFT_CLIENT_ID=$VITE_MICROSOFT_CLIENT_ID
ARG VITE_REPORTING_API
ENV VITE_REPORTING_API=$VITE_REPORTING_API

WORKDIR /app
COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:stable-alpine-slim as production
ENV NODE_ENV production

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]